import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations) ?? AppLocalizations(const Locale('en'));
  }

  static const LocalizationsDelegate<AppLocalizations> delegate = _AppLocalizationsDelegate();

  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'my_khata': 'My Khata',
      'dashboard': 'Dashboard',
      'clients': 'Clients',
      'all_clients': 'All Clients',
      'add_customer': 'Add Customer',
      'search': 'Search',
      'filter': 'Filter',
      'all': 'All',
      'you_will_get': 'You\'ll Get',
      'you_will_give': 'You\'ll Give',
      'cleared': 'Cleared',
      'recently_added': 'Recently Added',
      'customer_details': 'Customer Details',
      'entries': 'Entries',
      'you_gave': 'You Gave',
      'you_got': 'You Got',
      'hide_balance': 'Hide Balance',
      'show_balance': 'Show Balance',
      'total': 'Total',
      'save': 'Save',
      'cancel': 'Cancel',
      'delete': 'Delete',
      'edit': 'Edit',
      'share': 'Share',
      'pdf': 'PDF',
      'phone_number': 'Phone Number',
      'address': 'Address',
      'city': 'City',
      'cnic': 'CNIC',
      'notes': 'Notes',
      'item_category': 'Item Category',
      'cash': 'Cash',
      'bank': 'Bank',
      'online': 'Online',
      'update_customer': 'Update Customer',
      'add_new_customer': 'Add New Customer',
      'add_new_customer_vendor': 'Add New Customer / Vendor',
      'customer_name': 'Customer Name *',
      'vendor_name': 'Vendor / Shop Name *',
      'vendor': 'Vendor',
      'customer': 'Customer',
      'settings': 'Settings',
      'choose_language': 'Choose Language',
      'english': 'English',
      'urdu': 'اردو (Urdu)',
      'new_customer': 'New Customer',
      'save_customer': 'SAVE CUSTOMER',
      'delete_customer': 'Delete Customer',
      'delete_customer_msg': 'Are you sure you want to delete this customer?',
      'close': 'CLOSE',
      'amount': 'Amount',
      'date': 'Date',
      'add_transaction': 'Add Transaction',
      'update_transaction': 'Update Transaction',
      'transaction_type': 'Transaction Type?',
      'which_goods': 'Which Goods?',
      'weight': 'Weight',
      'today': 'Today',
      'transaction_saved': 'Transaction saved successfully',
      'select_date': 'Select Date',
      'purchased_goods': 'Purchased Goods',
      'sold_goods': 'Sold Goods',
      'cash_given': 'Cash Given',
      'cash_received': 'Cash Received',
      'rice': 'Rice',
      'scrap': 'Scrap',
      'other': 'Other',
      'details': 'Details / Tafseel',
      'backup_restore_title': 'Backup & Restore',
      'backup_restore_sub': 'Export or restore your khata data.',
      'backup_data': 'Backup Data',
      'backup_desc': 'Export all your data (Customers and Transactions) into a single JSON file.',
      'restore_data': 'Restore Data',
      'restore_desc': 'Import a previously saved JSON backup file. Existing data may be overwritten.',
      'choose_json': 'Choose JSON File',
      'backup_info': 'Only text data is stored inside the backup file. PDF receipts are not saved.',
      'danger_zone': 'Danger Zone',
      'delete_reset': 'Delete / Reset System',
      'delete_reset_desc': 'Permanently wipes Customers and Transactions. Your app settings stay safe.',
      'import_backup': 'Import Backup',
      'import_warning': 'This will overwrite your current data. Are you sure?',
      'import_success': 'Import Successful!',
      'import_failed': 'Import Failed',
      'delete_all_data': 'Delete All Data',
      'delete_all_warning': 'This action cannot be undone. Are you absolutely sure?',
      'all_data_deleted': 'All data deleted!',
      'export_complete': 'Export Complete!',
      'error': 'Error',
    },
    'ur': {
      'my_khata': 'میرا کھاتہ',
      'dashboard': 'ڈیش بورڈ',
      'clients': 'کلائنٹس',
      'all_clients': 'تمام کلائنٹس',
      'add_customer': 'گاہک شامل کریں',
      'search': 'تلاش کریں',
      'filter': 'فلٹر',
      'all': 'تمام',
      'you_will_get': 'آپ کو ملیں گے',
      'you_will_give': 'آپ دیں گے',
      'cleared': 'صاف شدہ (Cleared)',
      'recently_added': 'حال ہی میں شامل کیے گئے',
      'customer_details': 'گاہک کی تفصیلات',
      'entries': 'اندراجات',
      'you_gave': 'آپ نے دیے',
      'you_got': 'آپ کو ملے',
      'hide_balance': 'بیلنس چھپائیں',
      'show_balance': 'بیلنس دکھائیں',
      'total': 'کل',
      'save': 'محفوظ کریں',
      'cancel': 'منسوخ کریں',
      'delete': 'حذف کریں',
      'edit': 'ترمیم کریں',
      'share': 'شیئر کریں',
      'pdf': 'پی ڈی ایف',
      'phone_number': 'فون نمبر',
      'address': 'پتہ',
      'city': 'شہر',
      'cnic': 'شناختی کارڈ',
      'notes': 'نوٹس',
      'item_category': 'آئٹم کیٹیگری',
      'cash': 'کیش',
      'bank': 'بینک',
      'online': 'آن لائن',
      'update_customer': 'گاہک اپ ڈیٹ کریں',
      'add_new_customer': 'نیا گاہک شامل کریں',
      'add_new_customer_vendor': 'نیا گاہک / وینڈر شامل کریں',
      'customer_name': 'گاہک کا نام *',
      'vendor_name': 'وینڈر / دکان کا نام *',
      'vendor': 'وینڈر',
      'customer': 'گاہک',
      'settings': 'ترتیبات',
      'choose_language': 'زبان کا انتخاب کریں',
      'english': 'English',
      'urdu': 'اردو (Urdu)',
      'new_customer': 'نیا گاہک',
      'save_customer': 'گاہک محفوظ کریں',
      'delete_customer': 'گاہک حذف کریں',
      'delete_customer_msg': 'کیا آپ واقعی اس گاہک کو حذف کرنا چاہتے ہیں؟',
      'close': 'بند کریں',
      'amount': 'رقم',
      'date': 'تاریخ',
      'add_transaction': 'لین دین شامل کریں',
      'update_transaction': 'لین دین اپ ڈیٹ کریں',
      'transaction_type': 'لین دین کی قسم؟',
      'which_goods': 'کون سا مال؟',
      'weight': 'وزن',
      'today': 'آج',
      'transaction_saved': 'لین دین کامیابی سے محفوظ ہو گیا',
      'select_date': 'تاریخ منتخب کریں',
      'purchased_goods': 'مال خریدا',
      'sold_goods': 'مال بیچا',
      'cash_given': 'کیش دیا',
      'cash_received': 'کیش لیا',
      'rice': 'چاول',
      'scrap': 'اسکریپ',
      'other': 'دیگر',
      'details': 'تفصیل (Details)',
      'backup_restore_title': 'بیک اپ اور ری اسٹور',
      'backup_restore_sub': 'اپنے کھاتہ کا ڈیٹا محفوظ کریں یا واپس لائیں۔',
      'backup_data': 'ڈیٹا محفوظ کریں (بیک اپ)',
      'backup_desc': 'اپنا تمام ڈیٹا (کسٹمرز اور لین دین) ایک JSON فائل میں محفوظ کریں۔',
      'restore_data': 'ڈیٹا واپس لائیں (ری اسٹور)',
      'restore_desc': 'پہلے سے محفوظ کی گئی JSON بیک اپ فائل لائیں۔ موجودہ ڈیٹا ختم ہو سکتا ہے۔',
      'choose_json': 'JSON فائل منتخب کریں',
      'backup_info': 'بیک اپ میں صرف ٹیکسٹ ڈیٹا ہوتا ہے۔ پی ڈی ایف رسیدیں محفوظ نہیں ہوتیں۔',
      'danger_zone': 'خطرے کا علاقہ',
      'delete_reset': 'سسٹم ڈیلیٹ / ری سیٹ کریں',
      'delete_reset_desc': 'تمام کسٹمرز اور لین دین کو ہمیشہ کے لیے ختم کر دے گا۔ آپ کی ایپ کی سیٹنگز محفوظ رہیں گی۔',
      'import_backup': 'بیک اپ امپورٹ کریں',
      'import_warning': 'یہ آپ کا موجودہ ڈیٹا ختم کر دے گا۔ کیا آپ کو یقین ہے؟',
      'import_success': 'امپورٹ کامیاب ہو گیا!',
      'import_failed': 'امپورٹ ناکام ہو گیا',
      'delete_all_data': 'تمام ڈیٹا ڈیلیٹ کریں',
      'delete_all_warning': 'یہ عمل واپس نہیں ہو سکتا۔ کیا آپ کو پورا یقین ہے؟',
      'all_data_deleted': 'تمام ڈیٹا ڈیلیٹ ہو گیا!',
      'export_complete': 'ایکسپورٹ مکمل ہو گیا!',
      'error': 'خرابی',
    },
  };

  String translate(String key) {
    return _localizedValues[locale.languageCode]?[key] ?? _localizedValues['en']?[key] ?? key;
  }
}

class _AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['en', 'ur'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}
